name: Ubuntu_Server
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
    - uses: actions/checkout@v2
    - run: source ubuntu-run.sh
    - name: initialization
      run: |
           git config --global user.name "ElytrA8"
           git config --global user.email "manofuranium@gmail.com"             
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@master
